### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by akamiru** [akamiru/bce-next#1]
- [x] Add main encoding loop
- [x] Add main decoding loop
  - [x] Implement scatter update to the rank dictionary
     - [x] Use permi2d and 2 epi64 scatter to minimize port 4 pressure - on hold
       - Doing independant mask scatter for the rank allows to never gather it
       - 64bit scatters save >30 µops greatly improving usage of ROB
       - Rank gather is cache miss free and only 5 µops
     - [x] Set n_1w0 bits to the left of j
     - [x] Cear n_0w1 bits to the right of j
     - [x] Combine bits, clear and set with a single ternary logic op into a toggle mask
     - [x] Add logarithm conflict resolution
     - [x] Adjust the previous rank correctly
- [ ] Add first/last stage for encoding / decoding
  - [x] Add preloading values into the cache
  - [ ] Complete queue writeout (first) / no cache fill (last)
    - [ ] Encoding
    - [ ] Decoding
- [x] Add ANS encode / decode
  - [x] Use 23 bit precision for values smaller 32
    - The integer decode has a bit more µops but far less latency compared to float decode. If we're going to use the integer decode we could go up to 27 bits to increase precision but that probably is insignificant and drops the possiblity to switch to floating point decode later.
  - [x] Use 52 bit precision for values above 31
    - This allows to use double division and the upcoming IFMA
  - [ ] Implement correct flushing/loading
  - Encoding
    - [ ] Moving the shuffle further down might hide additional latency
- [ ] Code cleanup
 - [ ] Remove unused code fragments - Git keeps them for us
 - [ ] Check whitespace
- [ ] Add clue code (tie everything together)
  - [ ] Queue Management
  - [ ] Coder Management
- [ ] Testing of the actual compression / decompression
  - Use avx2 version for dictionary construction
- [ ] Add Wavelett matrix construction / deconstruction
  - [ ] Validate prefix sum + permutexvar for compress/expand for 64 bytes chunks
  - [ ] Validate pcompress / pexpand for 16 bytes each
  - [ ] Use already quite fast AVX2 version as fallback
- [ ] Add Suffix Sorting (daware)
  - [ ] Validate pcompress for quicksort (See Fast Sorting Algorithms using
AVX-512 on Intel Knights Landing - Bramas)
  - [ ] Validate gather + pcompress for multi-key quicksort
  - [ ] Validate parallel sorting networks for small chunks

**Comment by akamiru** [comment]
### ANS Notes

We can do 22 bit integer math using single precision floats. Shifting out 8 bits at a time we need exact division of 22 bit by 8 bit. This code can do it in 4 instructions (5 cycles throughput, 18 cycles latency). maybe it needs software pipelining. Direct integer division has (10 cycles on one port, 18 cycles latency).

    __m512 _mm512_divf_epi22(__m512 a, __m512 b) {
      auto rcp = _mm512_rcp14_ps(b);
      // newton iteration
      b = _mm512_fnmadd_ps(a, rcp, _mm512_set1_ps(2.0));
      rcp = _mm512_mul_ps(rcp, b);
      // divide
      const float const05f = -0.5 + 1.0 / 513;
      return _mm512_fmsub_round_ps(a, rcp, _mm512_set1_ps(const05f), _MM_FROUND_TO_NEAREST_INT |_MM_FROUND_NO_EXC);
    }
